<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.crate</groupId>
        <artifactId>crate</artifactId>
        <version>6.5.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.courseProjectCode</groupId>
    <artifactId>Course-Project-Code</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
            <version>3.28.2</version>
        </dependency>
    </dependencies>
</project>
